### PR TITLE
Pull mqtt_root_topic from config.yaml

### PR DESCRIPTION
**Pull request by lucboudreau**

### CODE REVIEW

**Comment by titilambert** [comment]
Thanks ! Please note that you can already change the root topic using the env var `ROOT_TOPIC`

**Comment by lucboudreau** [comment]
re: ROOT_TOPIC - I saw that, but this has a system wide effect. I need to control where the hydroquebec data is nested separately.

**Comment by titilambert** [comment]
> re: ROOT_TOPIC - I saw that, but this has a system wide effect. I need to control where the hydroquebec data is nested separately.

I understand and I agree !
I just want to avoid a breaking change.
So could you replace:
```
self.mqtt_root_topic = self.config.get('mqtt_root_topic', '')
```
By
```
if 'mqtt_root_topic' in self.config
    self.mqtt_root_topic = self.config['mqtt_root_topic']
```
With this the `self.mqtt_root_topic` variable will not be touched if the variable is not defined in the yaml and the env var will be still read.

**Comment by lucboudreau** [comment]
Sure. I'll take a look later today. I didn't test this stuff either, so mea-culpa.

**Comment by titilambert** [comment]
No problemo ! We could do the same thing for the other mqtt variables if needed

**Comment by lucboudreau** [comment]
Resubmitted as https://github.com/titilambert/pyhydroquebec/pull/55/files

**Pull request closed without merging**
