### PR TITLE
Added temperature data

### PR DESCRIPTION
**Pull request by diogos88**

### CODE REVIEW

**Comment by titilambert** [comment]
Thanks !

**Comment by titilambert** [comment]
@diogos88 Could you add
```
# -*- coding: utf-8 -*-
```
At the begining of `__main__.py` to keep the compatibility with python 2.7 ?

**Comment by diogos88** [comment]
Done

**Comment by titilambert** [comment]
Thanks !

**Comment by titilambert** [comment]
Released in 1.1.0 version (just pushed on Pypi)

**Pull request merged**
