### PR TITLE
Fix #32 by moving the version variable to a generic file.

### LINKED ISSUE #32: No module named 'aiohttp'
**Describe the bug**
Installation of the package fails due to the setup script requiring `aiohttp` prior due to how the module is loaded to obtain the version prior to requirements installation.

**To Reproduce**
1. Create an empty virtual environment (`python -m venv venv`)
2. Activate the environment (`.\venv\scripts\activate`)
3. Attempt to install the package (`pip install pyhydroquebec`)

```
Collecting pyhydroquebec
  Downloading https://files.pythonhosted.org/packages/50/dd/ea8437dfacfa7b758b98574a016b662b67acc7641e97e07b2c9ac45951c3/pyhydroquebec-2.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "Temp\pip-install-xdmsft7t\pyhydroquebec\setup.py", line 4, in <module>
        from pyhydroquebec.__main__ import VERSION
      File "Temp\pip-install-xdmsft7t\pyhydroquebec\pyhydroquebec\__init__.py", line 2, in <module>
        from pyhydroquebec.client import HydroQuebecClient, REQUESTS_TIMEOUT, HQ_TIMEZONE  # NOQA
      File "Temp\pip-install-xdmsft7t\pyhydroquebec\pyhydroquebec\client.py", line 7, in <module>
        import aiohttp
    ModuleNotFoundError: No module named 'aiohttp'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in Temp\pip-install-xdmsft7t\pyhydroquebec\
```

**Expected behavior**
Package setup script should be able to run without assumed dependencies.

**PyHydroQuebec and Python version**
pyhydroquebec 2.4.0, any supported python version.

### PR DESCRIPTION
**Pull request by ncareau**
The bug was initiated by setup-tools unable to build the application without loading the application which require dependencies that are not yet installed.

Fixed it by moving the version variable to it's own file with no dependencies at all and including this file in both the application and setup tools.

Fixes #32

### CODE REVIEW

**Comment by ncareau** [comment]
@titilambert Let me know what you prefer and i'll make sure to fix this.

**Comment by ThierryBegin** [comment]
Any news on that PR? Apparently it would also fix https://github.com/home-assistant/home-assistant/issues/24498 :)

**Comment by titilambert** [comment]
Thanks !
Sorry for the delay, I just got my :baby:

**Comment by ThierryBegin** [comment]
Thanks a bunch! and congratz for the baby!

**Comment by ncareau** [comment]
Don't worry for the delay, and congrats on the kid. Funny enough, just had a kid 4 months ago 😄 

Could you create a release with fixes ? I think this would help for home assistant and other software that relies on versioning.

**Pull request merged**
